### PR TITLE
Map puppetcode dir for 1st module testing

### PR DESCRIPTION
**Pull request by samuelson**
'/root/puppetcode' is the default, but it's not used in the course. This maps '/var/puppetcode' instead as a convenient way of getting the solutions to the container for the acceptance test while not distracting the students in class.

### CODE REVIEW

**Comment by binford2k** [comment]
What about adding a variable like `$classroom::params::testdir` or the like? That way all the courses needing it could use it, and then if you needed to change it for some reason, you could do it in one place.

**Comment by samuelson** [comment]
@binford2k like that?

**Comment by samuelson** [comment]
Whoops, thanks.

**Comment by binford2k** [comment]
Oh... I thought I'd merged this!

**Pull request merged**
