### PR TITLE
Install a krb5.conf with the expected configuration.

### PR DESCRIPTION
**Pull request by greglarkin**

### CODE REVIEW

**Comment by binford2k** [comment]
hmm. Actually.... I kind of like this error. It illustrates really well the problems with expecting to just manipulate lines in a file, or use grep or awk for a fact, or some such. Let me noodle on it :)

**Comment by greglarkin** [comment]
Oh yeah, that makes sense. The grep command could be more restrictive to get the desired result and filter out comments.

**Comment by binford2k** [comment]
@greglarkin I'm thinking that I like this note better, https://github.com/puppetlabs/courseware/commit/a3ff271cd209199e0f447a3f55c4c2d1f0a5b862

Do you approve of that approach?

**Comment by greglarkin** [comment]
Yes, that works for me @binford2k

**Pull request closed without merging**
