### PR TITLE
Add Spec tests for courses

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Added spec tests to check that each course actually compiles. It is also fully integrated with Travis which I would definitely recommend we use. (You guys will need to actually enable the repo from the travis side)

### CODE REVIEW

**Comment by binford2k** [comment]
This is actually a bigger PR than I was expecting. I'm going to delay this one until after PuppetConf so it can get reviewed the way it deserves. Thanks for starting this!

**Comment by dylanratcliffe** [comment]
@binford2k Can we get this one looked at now that PuppetConf is over?

**Comment by binford2k** [comment]
@dylanratcliffe will do very soon. You might also be interested in the beginnings of some real student testing too. https://github.com/puppetlabs/courseware-virtual/tree/master/fundamentals/_files/tests

**Comment by samuelson** [comment]
@dylanratcliffe sorry this has sat for so long, we'll fix it and merge

**Comment by samuelson** [comment]
I think that we've duplicated all of this now.  Sorry we didn't do this sooner @dylanratcliffe

**Pull request closed without merging**
