### PR TITLE
Use alternate puppetcode dir for parser

### PR DESCRIPTION
**Pull request by samuelson**

### CODE REVIEW

**Comment by carthik** [comment]
@samuelson : Could you add a note as to why we need to use that dir instead of another? Sorry for the trouble.

**Comment by samuelson** [comment]
@carthik the default is /root/puppetcode, which is not used in the puppet 4 parser course. So this puts the directory somewhere inconspicuous.

**Comment by carthik** [comment]
I'll merge this- having that in the commit message might be handy.

**Comment by samuelson** [comment]
ok, sorry I thought I had at the time

**Pull request merged**
