### PR TITLE
WIP: only set .ssh permissions on Linux

### PR DESCRIPTION
**Pull request by binford2k**
Ethan suggested not setting these permissions on Windows, thinking that it might be affecting the key permissions. I'm not convinced, because I think ssh will complain about permissions. Still, we should test it and find out.

If it does, then maybe we need to be using the acl module instead?

### CODE REVIEW

**Comment by Nekototori** [comment]
Of note, you don't want to remove the whole resource, but just remove the mode setting.  There are dependencies on it.

However, in testing it with mode removed, it does seem to prevent access denied errors.

**Comment by carthik** [comment]
We need to preserve the mode setting for *nix machines though.

**Comment by Nekototori** [comment]
It would be something more like the below:
`case $::osfamily {
    'windows' : {
      $environment         = undef
      $path                = 'C:/Program Files/Git/bin'
      $sshpath             = 'C:/Program Files/Git/.ssh'
      $sshpath_permissions = undef
    }
    default   : {
      $environment = 'HOME=/root'
      $path        = '/usr/bin:/bin:/user/sbin:/usr/sbin'
      $sshpath     = '/root/.ssh'
      $sshpath_permissions = '0600'
    }
  }`

`  file { $sshpath:
    ensure => directory,
    mode   => $sshpath_permissions
  }`

**Comment by binford2k** [comment]
@Nekototori how about this?

**Comment by binford2k** [comment]
This PR is no longer relevant. This class is only included in Puppetize now--and I don't think it's even required there either.

**Pull request closed without merging**
