### PR TITLE
Use the RPM already cached in the Yum repository

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by carthik** [comment]
What creates /home/git?
Also, why is the change needed? Can that go in the commit message?

**Comment by greglarkin** [comment]
@carthik I'll check, but I think the gitea RPM install script creates that directory?

**Comment by carthik** [comment]
I guess it makes sense to use the cached package and that's what changes here. Thanks.

**Comment by greglarkin** [comment]
And the `golang` package was removed because it's not a runtime dep of the gitea service.

**Pull request merged**
