### PR TITLE
READY FOR MERGE: Added Hiera lookup for environment to support Fundamentals labs

### PR DESCRIPTION
**Pull request by greglarkin**

### CODE REVIEW

**Comment by binford2k** [comment]
We'll review & merge these next tuesday, 9/27

**Comment by binford2k** [comment]
merge after 10/11

**Comment by greglarkin** [comment]
@binford2k Of course, now this PR conflicts with the new CS standard, so I guess I'll need to update courseware to handle that: https://github.com/puppetlabs/cs-standards/pull/30

**Comment by binford2k** [comment]
ha

**Pull request merged**
