### PR TITLE
Ensure that /etc/issue always has the current IP address

### PR DESCRIPTION
**Pull request by abuxton**
new class to update /etc/issue on *nix hosts, It's a pet peeve logging in to find out new ipaddress after first hour, second day etc

### CODE REVIEW

**Comment by binford2k** [comment]
I like this concept. I wonder if it should be a job for `rc.local` instead though. What do you think, @samuelson?

**Comment by samuelson** [comment]
@binford2k @abuxton here be dragons. You need to make sure that $ipaddress is always the primary ip (which is why I have all that crazy stuff in rc.local related to the default route). We were having the docker ip show up on that page.

If you can come up with a way to make sure it's right, I'm all for adding this.

**Comment by samuelson** [comment]
For reference: https://github.com/puppetlabs/pltraining-bootstrap/blob/master/templates/rc.local.erb#L34

**Comment by binford2k** [comment]
@samuelson should this be closed?

**Comment by samuelson** [comment]
I think we need a custom fact for this if we want to do it in puppet. It needs to look at the default gateway and use that to derive the primary IP. Honestly that's what the built in fact ought to do, but it doesn't.

**Pull request closed without merging**
