### PR TITLE
Traintech 713

### PR DESCRIPTION
**Pull request by josephoaks**
This is to update what has been done so far, still work in progress and the assert private needs to be worked on.

### CODE REVIEW

**Comment by binford2k** [comment]
Can you update the title to `WIP: whatever the PR adds`

**Comment by binford2k** [comment]
ping @josephoaks can you update the title as requested and update the PR?

**Comment by carthik** [comment]
@josephoaks is this complete? Can you please rebase this so it can be reviewed and merged, if it is complete?

**Comment by binford2k** [comment]
@josephoaks I'm closing this PR since comments haven't been addressed. If you'd like to continue working on it, feel free to reopen and correct the title or create a new PR with the title set properly.

**Pull request closed without merging**
