### PR TITLE
Fix the grep command in the docker tag exec to make it idempotent

### PR DESCRIPTION
**Pull request by greglarkin**
TRAINTECH-609 #resolved #time 30m

### CODE REVIEW

**Comment by samuelson** [comment]
@greglarkin I'm confused as to why this would make a difference. Aren't you just replacing the string
"centos:7" with "centos:7"? Am I missing something?

**Comment by samuelson** [comment]
oh nm, I see it now

**Comment by greglarkin** [comment]
@samuelson I think I noted in the JIRA ticket that the Puppet run is still not idempotent (a single resource), but it's because of code in the docker module and no longer anything in the classroom module.

**Comment by samuelson** [comment]
Yeah I saw that, I had just missed the spot where just image_name was used, so it looked like this didn't change anything.

**Pull request merged**
