### PR TITLE
Commit stash

### PR DESCRIPTION
**Pull request by joshsamuelson**
I took out the stashing because it seems like that was breaking things.  The staged files will get dropped back in without popping the stash when the commit fails, so I think that was redundant.

Now what happens is that working dir changes are saved in /tmp/stash.whatever and the staged changes are still checked for syntax.  If something goes wrong, the staged changes stay around and the working dir changes git applied from the /tmp/stash.whatever.

Please test this out for edge cases before merging.

### CODE REVIEW

**Comment by binford2k** [comment]
This is only validating the files on disk now, which may have changed since your last `git add`. That's the point of the stash.

**Comment by joshsamuelson** [comment]
So, if you've staged broken changes and then fixed them in the working dir, it won't catch them.  Is that the issue?

**Comment by binford2k** [comment]
Yep. If you fix, but don't add, then that would let you commit broken code.

**Comment by joshsamuelson** [comment]
yeah, I see it.  I think we need to only stash the staged changes

**Comment by joshsamuelson** [comment]
Meh, I can't get this to work the way I want it to.  As I see it, it should:
1. Stash the uncommited working tree
2. Test if the staged changes are valid
3. Commit the staged changes if valid or throw an error.
4. Put the working tree files back.

Maybe I need to put number 4 in a post-commit hook?

**Comment by joshsamuelson** [comment]
Ok, I'm giving up on this.  It doesn't seem possible to restore the stage and working tree separately.  Stash pop tries to commit the changes even if they weren't added before, which messes things up.

**Pull request closed without merging**
