### PR TITLE
Puppetize profile

### PR DESCRIPTION
**Pull request by samuelson**
Starting point for moving the other stuff over from the puppetfactory profile.

### CODE REVIEW

**Comment by binford2k** [comment]
Do we want to do a wrapper or just port wholesale like we started (and didn't finish) with the others, like https://github.com/puppetlabs/pltraining-classroom/blob/master/manifests/course/virtual/fundamentals.pp?

Or was your plan to do the wrapper so that we don't have to update docs when we get them all ported?

**Comment by samuelson** [comment]
I was just thinking let's to something low impact for now and we'll finish up after the initial delivery.

**Comment by binford2k** [comment]
Hokay, but you're committing to test it thoroughly prior to delivery!

Can you yank the params until they do something? I don't want them to be misleading.

**Comment by samuelson** [comment]
Well, maybe don't merge yet.  I think I might just finish the job since I'll have to test anyway.  I've got a lot of additional stuff to add for the master setup.

**Pull request merged**
